//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3C1O_Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3C1O_Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        internal static string A_CantConnet {
            get {
                return ResourceManager.GetString("A_CantConnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string A_Retry {
            get {
                return ResourceManager.GetString("A_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 200 的本地化字符串。
        /// </summary>
        internal static string A_Speed {
            get {
                return ResourceManager.GetString("A_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100 的本地化字符串。
        /// </summary>
        internal static string A_SpeedRead {
            get {
                return ResourceManager.GetString("A_SpeedRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1000 的本地化字符串。
        /// </summary>
        internal static string AutoEsc {
            get {
                return ResourceManager.GetString("AutoEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Bulb {
            get {
                object obj = ResourceManager.GetObject("Bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connection {
            get {
                object obj = ResourceManager.GetObject("connection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Finch 的本地化字符串。
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string Ia01 {
            get {
                return ResourceManager.GetString("Ia01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        internal static string Ia02 {
            get {
                return ResourceManager.GetString("Ia02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        internal static string Ia03 {
            get {
                return ResourceManager.GetString("Ia03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string Ia04 {
            get {
                return ResourceManager.GetString("Ia04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15 的本地化字符串。
        /// </summary>
        internal static string Ia05 {
            get {
                return ResourceManager.GetString("Ia05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 的本地化字符串。
        /// </summary>
        internal static string Ia06 {
            get {
                return ResourceManager.GetString("Ia06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 50 的本地化字符串。
        /// </summary>
        internal static string Ia07 {
            get {
                return ResourceManager.GetString("Ia07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100 的本地化字符串。
        /// </summary>
        internal static string Ia08 {
            get {
                return ResourceManager.GetString("Ia08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 150 的本地化字符串。
        /// </summary>
        internal static string Ia09 {
            get {
                return ResourceManager.GetString("Ia09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 200 的本地化字符串。
        /// </summary>
        internal static string Ia10 {
            get {
                return ResourceManager.GetString("Ia10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 250 的本地化字符串。
        /// </summary>
        internal static string Ia11 {
            get {
                return ResourceManager.GetString("Ia11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 300 的本地化字符串。
        /// </summary>
        internal static string Ia12 {
            get {
                return ResourceManager.GetString("Ia12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 350 的本地化字符串。
        /// </summary>
        internal static string Ia13 {
            get {
                return ResourceManager.GetString("Ia13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 400 的本地化字符串。
        /// </summary>
        internal static string Ia14 {
            get {
                return ResourceManager.GetString("Ia14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 450 的本地化字符串。
        /// </summary>
        internal static string Ia15 {
            get {
                return ResourceManager.GetString("Ia15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 500 的本地化字符串。
        /// </summary>
        internal static string Ia16 {
            get {
                return ResourceManager.GetString("Ia16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 550 的本地化字符串。
        /// </summary>
        internal static string Ia17 {
            get {
                return ResourceManager.GetString("Ia17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 600 的本地化字符串。
        /// </summary>
        internal static string Ia18 {
            get {
                return ResourceManager.GetString("Ia18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1000 的本地化字符串。
        /// </summary>
        internal static string LEDTime {
            get {
                return ResourceManager.GetString("LEDTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 3C1O-T 的本地化字符串。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 6298 的本地化字符串。
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Prohibit {
            get {
                object obj = ResourceManager.GetObject("Prohibit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string ReadAfterSet {
            get {
                return ResourceManager.GetString("ReadAfterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Semi_success {
            get {
                object obj = ResourceManager.GetObject("Semi_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 COM1 的本地化字符串。
        /// </summary>
        internal static string Serial1 {
            get {
                return ResourceManager.GetString("Serial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM2 的本地化字符串。
        /// </summary>
        internal static string Serial2 {
            get {
                return ResourceManager.GetString("Serial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM3 的本地化字符串。
        /// </summary>
        internal static string Serial3 {
            get {
                return ResourceManager.GetString("Serial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM4 的本地化字符串。
        /// </summary>
        internal static string Serial4 {
            get {
                return ResourceManager.GetString("Serial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM5 的本地化字符串。
        /// </summary>
        internal static string Serial5 {
            get {
                return ResourceManager.GetString("Serial5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 creat 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
